sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - BROWSERSTACK_USERNAME: dylanschiemann2
  - BROWSERSTACK_ACCESS_KEY: 4Q2g8YAc9qeZzB2hECnS
  - SAUCE_USERNAME: dojo2-ts-ci
  - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
  - FORCE_COLOR: 1
install:
- travis_retry npm install
script:
- npm test
- npm run uploadCoverage
